<h1><center>Shopee : Marketing Analysis</center><h1>

## Project Team â€“ Over30
- Donal Ngo         
- Lee Seng            
- Teerapong        
- Wilson Lum Kok Keong   
<br><br>

In [ ]:
from IPython.display import Image
Image(filename='diagram/Data_description.JPG')

<h2><center>Model Training & Testing</center><h2>

## Import Library

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# plot matplotlib graph
%matplotlib inline

#=========================================================================
# Next, we will import the required modules. Then we will define a generic 
# classification function, which takes a model as input and determines the 
# Accuracy and Cross-Validation scores.
#=========================================================================

#Import models from scikit learn module:
from sklearn.model_selection import KFold   #For K-fold cross validation
from sklearn import metrics 
from sklearn.metrics import f1_score
from sklearn.model_selection import cross_val_score
from sklearn.metrics import roc_curve, auc
from sklearn.metrics import classification_report
from sklearn.pipeline import Pipeline
from sklearn.model_selection import GridSearchCV
from matplotlib import pyplot as plt
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier, export_graphviz
from sklearn.ensemble.gradient_boosting import GradientBoostingClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
import pickle
from sklearn.externals import joblib

# import warnings filter
from warnings import simplefilter
import warnings
from pandas.core.common import SettingWithCopyWarning

# ignore all future warnings
simplefilter(action='ignore', category=FutureWarning)

# ignore all DataConversionWarning warnings
warnings.filterwarnings(action='ignore', category=SettingWithCopyWarning)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\deprecation.py:144: FutureWarning: The sklearn.ensemble.gradient_boosting module is  deprecated in version 0.22 and will be removed in version 0.24. The corresponding classes / functions should instead be imported from sklearn.ensemble. Anything that cannot be imported from sklearn.ensemble is now part of the private API.
  warnings.warn(message, FutureWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\externals\joblib\__init__.py:15: FutureWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
  warnings.warn(msg, category=FutureWarning)

## Reading dataset

In [2]:
#=========================================================================
# Read train data using pandas and first 5 rows of data
#=========================================================================

xls1    = pd.ExcelFile('data/test_dataset6_scaled.xlsx')
X_train = pd.read_excel(xls1, 'X_train_scaled')

dataset = X_train
features = ['attr_2', 'attr_3', 'subject_line_length', 'last_open_day',
       'last_login_day', 'last_checkout_day', 'open_count_last_10_days',
       'open_count_last_30_days', 'open_count_last_60_days',
       'login_count_last_10_days', 'login_count_last_30_days',
       'login_count_last_60_days', 'checkout_count_last_10_days',
       'checkout_count_last_30_days', 'checkout_count_last_60_days', 'weekday',
       'domain_@gmail.com', 'domain_@outlook.com', 'domain_@ymail.com',
       'country_code_1', 'country_code_2', 'country_code_3', 'country_code_4',
       'country_code_5', 'country_code_7']

dataset['row_id']    = 0
dataset['open_flag'] = 0

dataset.head()

,attr_2,attr_3,subject_line_length,last_open_day,last_login_day,last_checkout_day,open_count_last_10_days,open_count_last_30_days,open_count_last_60_days,login_count_last_10_days,...,domain_@outlook.com,domain_@ymail.com,country_code_1,country_code_2,country_code_3,country_code_4,country_code_5,country_code_7,row_id,open_flag
0,0.086621,-1.037198,-0.718757,-0.272080,-0.350077,-0.599259,0.094212,-0.312228,-0.421700,0.108118,...,-0.064057,-0.054146,-0.675130,-0.508441,-0.461336,-0.38418,-0.309754,-0.200289,0,0
1,0.086621,-1.037198,-0.718757,-0.347725,-0.330196,-0.140479,-0.315830,-0.628685,-0.698441,-0.271381,...,-0.064057,-0.054146,-0.675130,-0.508441,-0.461336,-0.38418,-0.309754,-0.200289,0,0
2,0.086621,0.913712,-1.617310,-0.245605,-0.356704,-0.611658,-0.725871,-0.786914,-0.790687,0.335817,...,-0.064057,-0.054146,-0.675130,-0.508441,-0.461336,-0.38418,3.228370,-0.200289,0,0
3,0.086621,0.913712,-0.628901,-0.135920,-0.330196,-0.609178,-0.725871,-0.786914,-0.790687,2.612807,...,-0.064057,-0.054146,1.481196,-0.508441,-0.461336,-0.38418,-0.309754,-0.200289,0,0
4,0.086621,-1.037198,-1.797021,-0.351507,-0.330196,-0.548421,-0.725871,-0.786914,-0.790687,-0.347280,...,-0.064057,-0.054146,-0.675130,-0.508441,-0.461336,-0.38418,3.228370,-0.200289,0,0

In [3]:
X_train.columns

Index(['attr_2', 'attr_3', 'subject_line_length', 'last_open_day',
       'last_login_day', 'last_checkout_day', 'open_count_last_10_days',
       'open_count_last_30_days', 'open_count_last_60_days',
       'login_count_last_10_days', 'login_count_last_30_days',
       'login_count_last_60_days', 'checkout_count_last_10_days',
       'checkout_count_last_30_days', 'checkout_count_last_60_days', 'weekday',
       'domain_@gmail.com', 'domain_@outlook.com', 'domain_@ymail.com',
       'country_code_1', 'country_code_2', 'country_code_3', 'country_code_4',
       'country_code_5', 'country_code_7', 'row_id', 'open_flag'],
      dtype='object')

In [4]:
dataset_copy = dataset.copy()
dataset_copy = pd.DataFrame(dataset_copy)
dataset_copy

,attr_2,attr_3,subject_line_length,last_open_day,last_login_day,last_checkout_day,open_count_last_10_days,open_count_last_30_days,open_count_last_60_days,login_count_last_10_days,...,domain_@outlook.com,domain_@ymail.com,country_code_1,country_code_2,country_code_3,country_code_4,country_code_5,country_code_7,row_id,open_flag
0,0.086621,-1.037198,-0.718757,-0.272080,-0.350077,-0.599259,0.094212,-0.312228,-0.421700,0.108118,...,-0.064057,-0.054146,-0.675130,-0.508441,-0.461336,-0.38418,-0.309754,-0.200289,0,0
1,0.086621,-1.037198,-0.718757,-0.347725,-0.330196,-0.140479,-0.315830,-0.628685,-0.698441,-0.271381,...,-0.064057,-0.054146,-0.675130,-0.508441,-0.461336,-0.38418,-0.309754,-0.200289,0,0
2,0.086621,0.913712,-1.617310,-0.245605,-0.356704,-0.611658,-0.725871,-0.786914,-0.790687,0.335817,...,-0.064057,-0.054146,-0.675130,-0.508441,-0.461336,-0.38418,3.228370,-0.200289,0,0
3,0.086621,0.913712,-0.628901,-0.135920,-0.330196,-0.609178,-0.725871,-0.786914,-0.790687,2.612807,...,-0.064057,-0.054146,1.481196,-0.508441,-0.461336,-0.38418,-0.309754,-0.200289,0,0
4,0.086621,-1.037198,-1.797021,-0.351507,-0.330196,-0.548421,-0.725871,-0.786914,-0.790687,-0.347280,...,-0.064057,-0.054146,-0.675130,-0.508441,-0.461336,-0.38418,3.228370,-0.200289,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55965,0.086621,-1.037198,0.898639,3.408020,-0.336823,-0.605459,-0.725871,-0.786914,-0.790687,-0.650879,...,-0.064057,-0.054146,-0.675130,-0.508441,-0.461336,-0.38418,-0.309754,-0.200289,0,0
55966,0.086621,-1.037198,0.898639,-0.151049,4.951413,0.881236,-0.725871,-0.786914,-0.698441,-0.650879,...,-0.064057,-0.054146,-0.675130,-0.508441,-0.461336,-0.38418,-0.309754,-0.200289,0,0
55967,0.086621,-1.037198,0.000086,3.408020,-0.316943,1.864512,-0.725871,-0.786914,-0.790687,-0.650879,...,-0.064057,-0.054146,-0.675130,-0.508441,-0.461336,-0.38418,-0.309754,-0.200289,0,0
55968,0.086621,-1.037198,0.000086,-0.355289,-0.330196,-0.607938,0.094212,0.004229,0.500767,-0.650879,...,-0.064057,-0.054146,-0.675130,-0.508441,-0.461336,-0.38418,-0.309754,-0.200289,0,0
55969,0.086621,-1.037198,0.898639,-0.355289,-0.343450,-0.590579,0.094212,1.428285,1.699974,-0.650879,...,-0.064057,-0.054146,-0.675130,-0.508441,-0.461336,-0.38418,-0.309754,-0.200289,0,0

In [5]:
dataset_copy1 = dataset.copy()
dataset_copy1 = pd.DataFrame(dataset_copy1)

In [6]:
dataset_copy2 = dataset.copy()
dataset_copy2 = pd.DataFrame(dataset_copy2)

In [7]:
dataset_copy3 = dataset.copy()
dataset_copy3 = pd.DataFrame(dataset_copy3)

<h2><center>Create Model and test</center><h2>

<h3>Random Forest Classifier<h3>

In [ ]:
## We can save the trained model clf using pickle 
filename = "model/Random_Forest_trained_model_dataset6.p"
model = pickle.load(open(filename, 'rb'))

In [ ]:
dataset.dtypes

In [ ]:
row = next(dataset.iterrows())[1]
row = row[features]
row

In [ ]:
row.astype(float)
row.dtypes

In [ ]:
row = pd.DataFrame(row)
row_t =row.T
row_t

In [ ]:
row_t.astype(float64)
row_t.dtypes

In [ ]:
predictions = model.predict(row_t)

In [ ]:
predictions

In [ ]:
pd.options.mode.chained_assignment = None  # default='warn'
for i, row in dataset.iterrows():
    if i%1000==0:
        print('batch:',i)
    row = row[features]
    row = pd.DataFrame(row)
    row_t =row.T
    predictions = model.predict(row_t)
    dataset['row_id'][i]    = i
    dataset['open_flag'][i] = predictions[0]

In [ ]:
dataset.columns

In [ ]:
dataset = dataset.drop(features, axis=1)
dataset

In [ ]:
dataset.to_csv('submit/Random_forest_dataset6-submission.csv', index=False)

<h3>Gradient Boosting Classifier<h3>

In [ ]:
## We can save the trained model clf using pickle 
filename = "model/Gradient_Boosting_Classifier_trained_model_dataset6.p"
model = pickle.load(open(filename, 'rb'))

In [ ]:
for i, row in dataset_copy.iterrows():
    if i%1000==0:
        print('batch:',i)
    row = row[features]
    row = pd.DataFrame(row)
    row_t =row.T
    predictions = model.predict(row_t)
    dataset_copy['row_id'][i]    = i
    dataset_copy['open_flag'][i] = predictions[0]

In [ ]:
dataset_copy

In [ ]:
dataset_copy = dataset_copy.drop(features, axis=1)
dataset_copy

In [ ]:
dataset_copy.to_csv('submit/Gradient_Boosting_classifier_dataset6-submission.csv', index=False)

<h3>K Nearest Neigbors KNN Model<h3>

In [ ]:
## We can save the trained model clf using pickle 
filename = "model/KNN_trained_model_dataset6.p"
model = pickle.load(open(filename, 'rb'))

In [ ]:
for i, row in dataset_copy2.iterrows():
    if i%1000==0:
        print('batch:',i)
    row = row[features]
    row = pd.DataFrame(row)
    row_t =row.T
    predictions = model.predict(row_t)
    dataset_copy2['row_id'][i]    = i
    dataset_copy2['open_flag'][i] = predictions[0]

In [ ]:
dataset_copy2 = dataset_copy2.drop(features, axis=1)
dataset_copy2

In [ ]:
dataset_copy2.to_csv('submit/KNN_dataset6-submission.csv', index=False)

<h3>Support Vector Machine Model<h3>

In [ ]:
## We can save the trained model clf using pickle 
filename = "model/SVM_trained_model_dataset6.p"
model = pickle.load(open(filename, 'rb'))

In [ ]:
for i, row in dataset_copy3.iterrows():
    if i%1000==0:
        print('batch:',i)
    row = row[features]
    row = pd.DataFrame(row)
    row_t =row.T
    predictions = model.predict(row_t)
    dataset_copy3['row_id'][i]    = i
    dataset_copy3['open_flag'][i] = predictions[0]

In [ ]:
dataset_copy3

In [ ]:
dataset_copy3 = dataset_copy3.drop(features, axis=1)
dataset_copy3

In [ ]:
dataset_copy3.to_csv('submit/SVM_dataset6-submission.csv', index=False)

<h3>Ensemble Model<h3>

In [8]:
features = ['attr_2', 'attr_3', 'subject_line_length', 'last_open_day',
       'last_login_day', 'last_checkout_day', 'open_count_last_10_days',
       'open_count_last_30_days', 'open_count_last_60_days',
       'login_count_last_10_days', 'login_count_last_30_days',
       'login_count_last_60_days', 'checkout_count_last_10_days',
       'checkout_count_last_30_days', 'checkout_count_last_60_days', 'weekday',
       'domain_@gmail.com', 'domain_@outlook.com', 'domain_@ymail.com',
       'country_code_1', 'country_code_2', 'country_code_3', 'country_code_4',
       'country_code_5', 'country_code_7']

In [9]:
## We can save the trained model clf using pickle 
filename = "model/Ensemble_Soft_model1_dataset6.p"
model = pickle.load(open(filename, 'rb'))

In [10]:
for i, row in dataset_copy1.iterrows():
    if i%1000==0:
        print('batch:',i)
    row = row[features]
    row = pd.DataFrame(row)
    row_t =row.T
    predictions = model.predict(row_t)
    dataset_copy1['row_id'][i]    = i
    dataset_copy1['open_flag'][i] = predictions[0]

batch: 0
batch: 1000
batch: 2000
batch: 3000
batch: 4000
batch: 5000
batch: 6000
batch: 7000
batch: 8000
batch: 9000
batch: 10000
batch: 11000
batch: 12000
batch: 13000
batch: 14000
batch: 15000
batch: 16000
batch: 17000
batch: 18000
batch: 19000
batch: 20000
batch: 21000
batch: 22000
batch: 23000
batch: 24000
batch: 25000
batch: 26000
batch: 27000
batch: 28000
batch: 29000
batch: 30000
batch: 31000
batch: 32000
batch: 33000
batch: 34000
batch: 35000
batch: 36000
batch: 37000
batch: 38000
batch: 39000
batch: 40000
batch: 41000
batch: 42000
batch: 43000
batch: 44000
batch: 45000
batch: 46000
batch: 47000
batch: 48000
batch: 49000
batch: 50000
batch: 51000
batch: 52000
batch: 53000
batch: 54000
batch: 55000

In [11]:
dataset_copy1

,attr_2,attr_3,subject_line_length,last_open_day,last_login_day,last_checkout_day,open_count_last_10_days,open_count_last_30_days,open_count_last_60_days,login_count_last_10_days,...,domain_@outlook.com,domain_@ymail.com,country_code_1,country_code_2,country_code_3,country_code_4,country_code_5,country_code_7,row_id,open_flag
0,0.086621,-1.037198,-0.718757,-0.272080,-0.350077,-0.599259,0.094212,-0.312228,-0.421700,0.108118,...,-0.064057,-0.054146,-0.675130,-0.508441,-0.461336,-0.38418,-0.309754,-0.200289,0,0
1,0.086621,-1.037198,-0.718757,-0.347725,-0.330196,-0.140479,-0.315830,-0.628685,-0.698441,-0.271381,...,-0.064057,-0.054146,-0.675130,-0.508441,-0.461336,-0.38418,-0.309754,-0.200289,1,0
2,0.086621,0.913712,-1.617310,-0.245605,-0.356704,-0.611658,-0.725871,-0.786914,-0.790687,0.335817,...,-0.064057,-0.054146,-0.675130,-0.508441,-0.461336,-0.38418,3.228370,-0.200289,2,0
3,0.086621,0.913712,-0.628901,-0.135920,-0.330196,-0.609178,-0.725871,-0.786914,-0.790687,2.612807,...,-0.064057,-0.054146,1.481196,-0.508441,-0.461336,-0.38418,-0.309754,-0.200289,3,0
4,0.086621,-1.037198,-1.797021,-0.351507,-0.330196,-0.548421,-0.725871,-0.786914,-0.790687,-0.347280,...,-0.064057,-0.054146,-0.675130,-0.508441,-0.461336,-0.38418,3.228370,-0.200289,4,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55965,0.086621,-1.037198,0.898639,3.408020,-0.336823,-0.605459,-0.725871,-0.786914,-0.790687,-0.650879,...,-0.064057,-0.054146,-0.675130,-0.508441,-0.461336,-0.38418,-0.309754,-0.200289,55965,0
55966,0.086621,-1.037198,0.898639,-0.151049,4.951413,0.881236,-0.725871,-0.786914,-0.698441,-0.650879,...,-0.064057,-0.054146,-0.675130,-0.508441,-0.461336,-0.38418,-0.309754,-0.200289,55966,0
55967,0.086621,-1.037198,0.000086,3.408020,-0.316943,1.864512,-0.725871,-0.786914,-0.790687,-0.650879,...,-0.064057,-0.054146,-0.675130,-0.508441,-0.461336,-0.38418,-0.309754,-0.200289,55967,0
55968,0.086621,-1.037198,0.000086,-0.355289,-0.330196,-0.607938,0.094212,0.004229,0.500767,-0.650879,...,-0.064057,-0.054146,-0.675130,-0.508441,-0.461336,-0.38418,-0.309754,-0.200289,55968,0
55969,0.086621,-1.037198,0.898639,-0.355289,-0.343450,-0.590579,0.094212,1.428285,1.699974,-0.650879,...,-0.064057,-0.054146,-0.675130,-0.508441,-0.461336,-0.38418,-0.309754,-0.200289,55969,1

In [12]:
dataset_copy1 = dataset_copy1.drop(features, axis=1)
dataset_copy1

       row_id  open_flag
0           0          0
1           1          0
2           2          0
3           3          0
4           4          0
...       ...        ...
55965   55965          0
55966   55966          0
55967   55967          0
55968   55968          0
55969   55969          1

[55970 rows x 2 columns]

In [13]:
dataset_copy1.to_csv('submit/Ensemble_dataset6-submission.csv', index=False)